import { useState, useEffect } from 'react';
import { Button } from '../ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../ui/card';
import { Badge } from '../ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { consentAPI, vitalsAPI, medicationsAPI, alertsAPI, notificationsAPI } from '../../utils/api';
import { Heart, Users, LogOut, Bell, Activity, Pill, AlertTriangle, Download, FileText } from 'lucide-react';
import { authAPI } from '../../utils/api';
import { toast } from 'sonner@2.0.3';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

interface DoctorDashboardProps {
  profile: any;
  onLogout: () => void;
}

export function DoctorDashboard({ profile, onLogout }: DoctorDashboardProps) {
  const [patients, setPatients] = useState<any[]>([]);
  const [selectedPatient, setSelectedPatient] = useState<any>(null);
  const [patientVitals, setPatientVitals] = useState<any[]>([]);
  const [patientMeds, setPatientMeds] = useState<any[]>([]);
  const [patientMedLogs, setPatientMedLogs] = useState<any[]>([]);
  const [patientAlerts, setPatientAlerts] = useState<any[]>([]);
  const [notifications, setNotifications] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadPatients();
    loadNotifications();
  }, []);

  useEffect(() => {
    if (selectedPatient) {
      loadPatientData(selectedPatient.id);
    }
  }, [selectedPatient]);

  const loadPatients = async () => {
    try {
      const response = await consentAPI.getPatients();
      setPatients(response.patients || []);
      if (response.patients && response.patients.length > 0) {
        setSelectedPatient(response.patients[0]);
      }
    } catch (error: any) {
      console.error('Error loading patients:', error);
      toast.error('Failed to load patient list');
    } finally {
      setLoading(false);
    }
  };

  const loadPatientData = async (patientId: string) => {
    try {
      const [vitalsRes, medsRes, logsRes, alertsRes] = await Promise.all([
        vitalsAPI.getHistory(patientId),
        medicationsAPI.getList(patientId),
        medicationsAPI.getLogs(patientId),
        alertsAPI.getList(patientId),
      ]);
      
      setPatientVitals(vitalsRes.vitals || []);
      setPatientMeds(medsRes.medications || []);
      setPatientMedLogs(logsRes.logs || []);
      setPatientAlerts(alertsRes.alerts || []);
    } catch (error: any) {
      console.error('Error loading patient data:', error);
      toast.error('Failed to load patient data');
    }
  };

  const loadNotifications = async () => {
    try {
      const response = await notificationsAPI.getList();
      setNotifications(response.notifications || []);
    } catch (error: any) {
      console.error('Error loading notifications:', error);
    }
  };

  const handleLogout = async () => {
    try {
      await authAPI.signout();
      toast.success('Logged out successfully');
      onLogout();
    } catch (error: any) {
      console.error('Logout error:', error);
      toast.error('Failed to logout');
    }
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString() + ' ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const prepareChartData = () => {
    return patientVitals
      .slice()
      .reverse()
      .slice(-30)
      .map((vital) => ({
        date: new Date(vital.timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
        systolic: vital.systolic,
        diastolic: vital.diastolic,
      }));
  };

  const calculateAdherence = () => {
    const last30Days = new Date();
    last30Days.setDate(last30Days.getDate() - 30);
    
    const recentLogs = patientMedLogs.filter(log => new Date(log.timestamp) >= last30Days);
    const takenLogs = recentLogs.filter(log => log.taken);
    
    if (recentLogs.length === 0) return 0;
    return Math.round((takenLogs.length / recentLogs.length) * 100);
  };

  const generateHealthSummary = () => {
    if (!selectedPatient) return;

    // Generate health summary report
    let report = `HEALTH SUMMARY REPORT\n`;
    report += `Generated by Dr. ${profile.name}\n`;
    report += `Date: ${new Date().toLocaleString()}\n\n`;
    
    report += `PATIENT INFORMATION\n`;
    report += `Name: ${selectedPatient.name}\n`;
    report += `Age: ${selectedPatient.age || 'N/A'}\n`;
    report += `Sex: ${selectedPatient.sex || 'N/A'}\n`;
    report += `Existing Conditions: ${selectedPatient.conditions || 'None reported'}\n\n`;
    
    report += `BLOOD PRESSURE SUMMARY\n`;
    report += `Total Readings: ${patientVitals.length}\n`;
    if (patientVitals.length > 0) {
      const avgSystolic = Math.round(patientVitals.reduce((sum, v) => sum + v.systolic, 0) / patientVitals.length);
      const avgDiastolic = Math.round(patientVitals.reduce((sum, v) => sum + v.diastolic, 0) / patientVitals.length);
      report += `Average BP: ${avgSystolic}/${avgDiastolic} mmHg\n`;
      report += `Latest Reading: ${patientVitals[0].systolic}/${patientVitals[0].diastolic} mmHg (${formatDate(patientVitals[0].timestamp)})\n`;
      
      const highReadings = patientVitals.filter(v => v.systolic >= 140 || v.diastolic >= 90).length;
      report += `High BP Readings: ${highReadings} (${Math.round((highReadings / patientVitals.length) * 100)}%)\n`;
    }
    report += `\n`;
    
    report += `MEDICATIONS\n`;
    const activeMeds = patientMeds.filter(m => m.active);
    report += `Active Medications: ${activeMeds.length}\n`;
    activeMeds.forEach(med => {
      report += `- ${med.name} ${med.dosage} (${med.schedule})\n`;
    });
    report += `\n`;
    
    report += `MEDICATION ADHERENCE\n`;
    const adherence = calculateAdherence();
    report += `30-Day Adherence Rate: ${adherence}%\n`;
    report += `Total Doses Logged: ${patientMedLogs.length}\n`;
    report += `Doses Taken: ${patientMedLogs.filter(l => l.taken).length}\n`;
    report += `Doses Missed: ${patientMedLogs.filter(l => !l.taken).length}\n\n`;
    
    report += `ALERTS & WARNINGS\n`;
    report += `Total Alerts: ${patientAlerts.length}\n`;
    report += `Critical Alerts: ${patientAlerts.filter(a => a.severity === 'critical').length}\n`;
    report += `Warning Alerts: ${patientAlerts.filter(a => a.severity === 'warning').length}\n\n`;
    
    if (patientAlerts.length > 0) {
      report += `Recent Alerts:\n`;
      patientAlerts.slice(0, 5).forEach(alert => {
        report += `- ${alert.message} (${formatDate(alert.timestamp)})\n`;
      });
    }
    
    report += `\n\nRECOMMENDATIONS\n`;
    report += `[Doctor's notes and recommendations to be added]\n`;

    // Download report
    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `health-summary-${selectedPatient.name.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    
    toast.success('Health summary report generated');
  };

  const unreadNotifications = notifications.filter(n => !n.read);
return (
    <div className="min-h-screen bg-gradient-to-br from-teal-50 via-white to-blue-50">
      {/* Top Navigation Bar */}
      <div className="bg-white border-b shadow-sm sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-3 sm:px-4 py-3 sm:py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 sm:gap-3">
              <div className="bg-teal-100 p-1.5 sm:p-2 rounded-full">
                <Heart className="w-5 h-5 sm:w-6 sm:h-6 text-teal-600" />
              </div>
              <div>
                <h1 className="text-base sm:text-xl font-semibold">WellCare Companion</h1>
                <p className="text-xs sm:text-sm text-gray-600 hidden sm:block">Healthcare Provider Portal</p>
              </div>
            </div>
            <div className="flex items-center gap-2 sm:gap-3">
              <div className="text-right mr-2 sm:mr-3 hidden md:block">
                <div className="text-sm font-medium">Dr. {profile.name}</div>
                {profile.specialization && (
                  <div className="text-xs text-gray-500">{profile.specialization}</div>
                )}
              </div>
              <div className="relative">
                <Button variant="outline" size="sm">
                  <Bell className="w-4 h-4" />
                  {unreadNotifications.length > 0 && (
                    <Badge className="absolute -top-2 -right-2 h-5 w-5 flex items-center justify-center p-0 text-xs">
                      {unreadNotifications.length}
                    </Badge>
                  )}
                </Button>
              </div>
              <Button variant="outline" size="sm" onClick={handleLogout}>
                <LogOut className="w-4 h-4 sm:mr-2" />
                <span className="hidden sm:inline">Logout</span>
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div className="max-w-7xl mx-auto px-4 py-6">
        {/* Welcome */}
        <div className="mb-6">
          <h2 className="text-2xl mb-1">Patient Management Dashboard</h2>
          <p className="text-gray-600">Monitor and review patient health records</p>
        </div>

        {loading ? (
          <Card>
            <CardContent className="text-center py-12 text-gray-400">
              Loading...
            </CardContent>
          </Card>
        ) : patients.length === 0 ? (
          <Card>
            <CardContent className="text-center py-12">
              <Users className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <h3 className="text-xl mb-2">No Patients Assigned</h3>
              <p className="text-gray-500 mb-4">
                You don't have access to any patient records yet.
              </p>
              <p className="text-sm text-gray-400">
                Patients can grant you access by adding your email address ({profile.email}) in their Data Sharing settings.
              </p>
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Patient List Sidebar */}
            <div className="lg:col-span-1">
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Patient List ({patients.length})</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  {patients.map((patient) => (
                    <button
                      key={patient.id}
                      onClick={() => setSelectedPatient(patient)}
                      className={`w-full text-left p-3 rounded-lg transition-colors ${
                        selectedPatient?.id === patient.id
                          ? 'bg-teal-100 border-2 border-teal-300'
                          : 'bg-gray-50 hover:bg-gray-100 border-2 border-transparent'
                      }`}
                    >
                      <div className="font-medium">{patient.name}</div>
                      <div className="text-xs text-gray-500 space-y-0.5">
                        {patient.age && <div>{patient.age} years • {patient.sex}</div>}
                        {patient.conditions && <div className="truncate">{patient.conditions}</div>}
                      </div>
                    </button>
                  ))}
                </CardContent>
              </Card>

              {/* Notifications */}
              {unreadNotifications.length > 0 && (
                <Card className="mt-4 border-orange-200 bg-orange-50">
                  <CardHeader>
                    <CardTitle className="text-base flex items-center gap-2 text-orange-900">
                      <Bell className="w-4 h-4" />
                      Alerts ({unreadNotifications.length})
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2">
                    {unreadNotifications.slice(0, 5).map((notif) => {
                      const patient = patients.find(p => p.id === notif.patientId);
                      return (
                        <div key={notif.id} className="p-2 bg-white rounded text-sm">
                          <div className="font-medium">{patient?.name}</div>
                          <div>{notif.message}</div>
                          <div className="text-xs text-gray-500 mt-1">
                            {formatDate(notif.timestamp)}
                          </div>
                        </div>
                      );
                    })}
                  </CardContent>
                </Card>
              )}
            </div>

            {/* Patient Details */}
            {selectedPatient && (
              <div className="lg:col-span-3 space-y-6">
                {/* Patient Header with Actions */}
                <Card>
                  <CardContent className="pt-6">
                    <div className="flex items-start justify-between mb-4">
                      <div>
                        <h3 className="text-2xl mb-2">{selectedPatient.name}</h3>
                        <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm text-gray-600">
                          {selectedPatient.age && <div><span className="font-medium">Age:</span> {selectedPatient.age}</div>}
                          {selectedPatient.sex && <div><span className="font-medium">Sex:</span> {selectedPatient.sex}</div>}
                          {selectedPatient.conditions && (
                            <div className="col-span-2"><span className="font-medium">Conditions:</span> {selectedPatient.conditions}</div>
                          )}
                          {selectedPatient.emergencyContact && (
                            <div className="col-span-2">
                              <span className="font-medium">Emergency Contact:</span> {selectedPatient.emergencyContact} ({selectedPatient.emergencyPhone})
                            </div>
                          )}
                        </div>
                      </div>
                      <Button onClick={generateHealthSummary}>
                        <FileText className="w-4 h-4 mr-2" />
                        Generate Report
                      </Button>
                    </div>
                  </CardContent>
                </Card>

                {/* Clinical Summary Cards */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <Card>
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <Activity className="w-8 h-8 text-red-500 mx-auto mb-2" />
                        <div className="text-2xl">{patientVitals.length}</div>
                        <div className="text-sm text-gray-500">BP Readings</div>
                        {patientVitals[0] && (
                          <Badge variant={
                            patientVitals[0].systolic >= 140 || patientVitals[0].diastolic >= 90 ? 'destructive' : 'default'
                          } className="mt-2">
                            {patientVitals[0].systolic}/{patientVitals[0].diastolic}
                          </Badge>
                        )}
                      </div>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <Pill className="w-8 h-8 text-blue-500 mx-auto mb-2" />
                        <div className="text-2xl">{patientMeds.filter(m => m.active).length}</div>
                        <div className="text-sm text-gray-500">Medications</div>
                      </div>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <Activity className="w-8 h-8 text-green-500 mx-auto mb-2" />
                        <div className="text-2xl">{calculateAdherence()}%</div>
                        <div className="text-sm text-gray-500">Adherence</div>
                      </div>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardContent className="pt-6">
                      <div className="text-center">
                        <AlertTriangle className="w-8 h-8 text-orange-500 mx-auto mb-2" />
                        <div className="text-2xl">{patientAlerts.length}</div>
                        <div className="text-sm text-gray-500">Total Alerts</div>
                      </div>
                    </CardContent>
                  </Card>
                </div>

                {/* Clinical Data Tabs */}
                <Tabs defaultValue="overview">
                  <TabsList>
                    <TabsTrigger value="overview">Overview</TabsTrigger>
                    <TabsTrigger value="vitals">Vital History</TabsTrigger>
                    <TabsTrigger value="medications">Medications</TabsTrigger>
                    <TabsTrigger value="adherence">Adherence</TabsTrigger>
                    <TabsTrigger value="alerts">Alerts</TabsTrigger>
                  </TabsList>

                  <TabsContent value="overview" className="space-y-4">
                    {/* BP Trends Chart */}
                    <Card>
                      <CardHeader>
                        <CardTitle>Blood Pressure Trends</CardTitle>
                        <CardDescription>Last 30 readings</CardDescription>
                      </CardHeader>
                      <CardContent>
                        {prepareChartData().length > 0 ? (
                          <ResponsiveContainer width="100%" height={300}>
                            <LineChart data={prepareChartData()}>
                              <CartesianGrid strokeDasharray="3 3" />
                              <XAxis dataKey="date" />
                              <YAxis domain={[40, 200]} />
                              <Tooltip />
                              <Legend />
                              <Line type="monotone" dataKey="systolic" stroke="#ef4444" name="Systolic" strokeWidth={2} />
                              <Line type="monotone" dataKey="diastolic" stroke="#3b82f6" name="Diastolic" strokeWidth={2} />
                            </LineChart>
                          </ResponsiveContainer>
                        ) : (
                          <div className="text-center py-12 text-gray-400">No data available</div>
                        )}
                      </CardContent>
                    </Card>

                    {/* Summary Statistics */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <Card>
                        <CardHeader>
                          <CardTitle className="text-base">BP Statistics</CardTitle>
                        </CardHeader>
                        <CardContent>
                          {patientVitals.length > 0 ? (
                            <div className="space-y-2 text-sm">
                              <div className="flex justify-between">
                                <span>Average Systolic:</span>
                                <span className="font-medium">
                                  {Math.round(patientVitals.reduce((sum, v) => sum + v.systolic, 0) / patientVitals.length)} mmHg
                                </span>
                              </div>
                              <div className="flex justify-between">
                                <span>Average Diastolic:</span>
                                <span className="font-medium">
                                  {Math.round(patientVitals.reduce((sum, v) => sum + v.diastolic, 0) / patientVitals.length)} mmHg
                                </span>
                              </div>
                              <div className="flex justify-between">
                                <span>High BP Readings:</span>
                                <span className="font-medium text-red-600">
                                  {patientVitals.filter(v => v.systolic >= 140 || v.diastolic >= 90).length}
                                </span>
                              </div>
                            </div>
                          ) : (
                            <div className="text-gray-400">No data</div>
                          )}
                        </CardContent>
                      </Card>

                      <Card>
                        <CardHeader>
                          <CardTitle className="text-base">Active Medications</CardTitle>
                        </CardHeader>
                        <CardContent>
                          <div className="space-y-2">
                            {patientMeds.filter(m => m.active).slice(0, 3).map(med => (
                              <div key={med.id} className="text-sm">
                                <div className="font-medium">{med.name}</div>
                                <div className="text-gray-500">{med.dosage} - {med.schedule}</div>
                              </div>
                            ))}
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </TabsContent>

                  <TabsContent value="vitals">
                    <Card>
                      <CardHeader>
                        <CardTitle>Complete Vital Signs History</CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-2">
                        {patientVitals.map((vital) => (
                          <div key={vital.id} className="p-3 border rounded-lg">
                            <div className="flex items-center gap-2">
                              <span className="text-lg font-medium">{vital.systolic}/{vital.diastolic} mmHg</span>
                              {(vital.systolic >= 140 || vital.diastolic >= 90) && (
                                <Badge variant="destructive">High</Badge>
                              )}
                              {vital.pulse && <Badge variant="outline">♥ {vital.pulse} bpm</Badge>}
                            </div>
                            <div className="text-sm text-gray-500 mt-1">{formatDate(vital.timestamp)}</div>
                            {vital.notes && (
                              <div className="text-sm text-gray-600 mt-2 p-2 bg-gray-50 rounded">
                                <span className="font-medium">Notes:</span> {vital.notes}
                              </div>
                            )}
                          </div>
                        ))}
                      </CardContent>
                    </Card>
                  </TabsContent>

                  <TabsContent value="medications">
                    <Card>
                      <CardHeader>
                        <CardTitle>Medication Regimen</CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-3">
                        {patientMeds.map((med) => (
                          <div key={med.id} className="p-4 border rounded-lg">
                            <div className="flex items-center justify-between mb-2">
                              <div className="flex items-center gap-2">
                                <span className="font-medium text-lg">{med.name}</span>
                                <Badge variant="outline">{med.dosage}</Badge>
                              </div>
                              <Badge variant={med.active ? 'default' : 'secondary'}>
                                {med.active ? 'Active' : 'Inactive'}
                              </Badge>
                            </div>
                            {med.schedule && (
                              <div className="text-sm text-gray-600 mb-1">
                                <span className="font-medium">Schedule:</span> {med.schedule}
                              </div>
                            )}
                            {med.notes && (
                              <div className="text-sm text-gray-600 p-2 bg-gray-50 rounded mt-2">
                                <span className="font-medium">Notes:</span> {med.notes}
                              </div>
                            )}
                          </div>
                        ))}
                      </CardContent>
                    </Card>
                  </TabsContent>

                  <TabsContent value="adherence">
                    <Card>
                      <CardHeader>
                        <CardTitle>Medication Adherence Analysis</CardTitle>
                        <CardDescription>30-day adherence rate: {calculateAdherence()}%</CardDescription>
                      </CardHeader>
                      <CardContent className="space-y-2">
                        {patientMedLogs.slice(0, 20).map((log) => {
                          const med = patientMeds.find(m => m.id === log.medicationId);
                          if (!med) return null;
                          
                          return (
                            <div key={log.id} className="flex items-center gap-3 p-3 border rounded-lg">
                              <div className={`w-3 h-3 rounded-full ${log.taken ? 'bg-green-500' : 'bg-red-500'}`} />
                              <div className="flex-1">
                                <div className="flex items-center gap-2">
                                  <span className="font-medium">{med.name}</span>
                                  <Badge variant="outline">{med.dosage}</Badge>
                                  <Badge variant={log.taken ? 'default' : 'destructive'}>
                                    {log.taken ? 'Taken' : 'Missed'}
                                  </Badge>
                                </div>
                                <div className="text-sm text-gray-500">{formatDate(log.timestamp)}</div>
                              </div>
                            </div>
                          );
                        })}
                      </CardContent>
                    </Card>
                  </TabsContent>

                  <TabsContent value="alerts">
                    <Card>
                      <CardHeader>
                        <CardTitle>Clinical Alerts & Warnings</CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-2">
                        {patientAlerts.map((alert) => (
                          <div key={alert.id} className={`p-4 rounded-lg border-2 ${
                            alert.severity === 'critical' ? 'bg-red-50 border-red-200' : 'bg-orange-50 border-orange-200'
                          }`}>
                            <div className="flex items-start gap-3">
                              <AlertTriangle className={`w-5 h-5 mt-0.5 ${
                                alert.severity === 'critical' ? 'text-red-600' : 'text-orange-600'
                              }`} />
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-1">
                                  <span className="font-medium">{alert.type.replace('_', ' ').toUpperCase()}</span>
                                  <Badge variant={alert.severity === 'critical' ? 'destructive' : 'secondary'}>
                                    {alert.severity}
                                  </Badge>
                                </div>
                                <div className="text-sm">{alert.message}</div>
                                <div className="text-sm text-gray-600 mt-1">
                                  {formatDate(alert.timestamp)}
                                </div>
                              </div>
                            </div>
                          </div>
                        ))}
                      </CardContent>
                    </Card>
                  </TabsContent>
                </Tabs>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
